### PR TITLE
add flow charts that document the Roadblock protocol and bus mirroring

### PR DESCRIPTION
**Pull request by k-rister**

### CODE REVIEW

**Comment by k-rister** [comment]
To see what this actually looks like: https://github.com/k-rister/roadblock/tree/docs

**Comment by tc-wilson** [comment]
Nice charts!  :-)

**Review by tc-wilson — APPROVED** [review]
Nice charts!  :-)

**Review by HughNhan — APPROVED** [review]
Great information!!!

**Review by atheurer — APPROVED** [review]

**Pull request merged**
