### PR TITLE
Dev kmr

### PR DESCRIPTION
**Pull request by k-rister**

### CODE REVIEW

**Comment by k-rister** [comment]
@rafaelfolco @atheurer 

Can you guys look over this?  I think its ready functionality wise, but I'm not completely sold on some of the terminology I used (--wait-for?) and I'm curious if there are better ideas out there.  I still need to clean it up some and if I'm going to make terminology changes then doing so in conjunction with cleaning up the code would probably be the easiest way.

**Comment by atheurer** [comment]
One thing I am not sure of, when a participant uses --wait-for and the subprocess fails, it sends a message with "follower-waiting-complete-failed".  Can we also send additional messages, like the output from the subprocess?  I think we need something like this, otherwise we won't know why it failed.

I many situations I think this new way of using roadblock has to replace the way we use some aborts today.  The challenge is that the current way, we ran a roadblock (client-start), then ran a process (benchmark), then checked for outcome of that process (benchmark failed), then sent an abort on the next roadblock (client-stop).  I need to wrap my head around this will work with the new feature.  It sounds like, in this example, the client-stop roadblock would run with --wait-for, and --wait-for would run the benchmark client command.

**Comment by k-rister** [comment]
> One thing I am not sure of, when a participant uses --wait-for and the subprocess fails, it sends a message with "follower-waiting-complete-failed". Can we also send additional messages, like the output from the subprocess? I think we need something like this, otherwise we won't know why it failed.

This is doable.  I think we just have to decide if we want to send the entire output (which could potentially be quite large) and let the receiver process it or if we want to attempt to do some kind of processing ourselves to reduce the payload size.

> 
> I many situations I think this new way of using roadblock has to replace the way we use some aborts today. The challenge is that the current way, we ran a roadblock (client-start), then ran a process (benchmark), then checked for outcome of that process (benchmark failed), then sent an abort on the next roadblock (client-stop). I need to wrap my head around this will work with the new feature. It sounds like, in this example, the client-stop roadblock would run with --wait-for, and --wait-for would run the benchmark client command.

I've sorta been thinking about this while working on this new feature.  I think there is potential to replace all of our existing roadblock calls with this new support, but I'm not convinced there is a compelling reason to do so.  There are probably some situations that would benefit from this but I'm not sure that all would.  If there are situations that don't really gain anything from the new methodology then I'm not sure we should spend the time completely reworking the code.

Plus, we still have the potential problem with the new methodology that we can now wait forever if the script/program we are calling doesn't return -- so we may want to continue the older methodology in some situations to maintain some time bounding for certain activities.

**Comment by k-rister** [comment]
@atheurer 

```
$ ./roadblock.py --role leader --leader-id foo --followers bar --followers zorg --redis-password flubber --timeout 10 --message-log leader.message-log.out --uuid 74
...

$ jq --raw-output '.received[].payload.message | select(.command=="follower-waiting-complete-failed") | .value' leader.message-log.out | base64 --decode | xz --decompress --stdout | head
argument 1: 75
argument 2: foo
argument 3: bar
argument 4: this is a test
Expected runtime: 75 seconds
STDOUT at Sat Jan 29 16:17:07 UTC 2022
STDERR at Sat Jan 29 16:17:07 UTC 2022
1: Sat Jan 29 16:17:07 UTC 2022
2: Sat Jan 29 16:17:08 UTC 2022
3: Sat Jan 29 16:17:09 UTC 2022
```

**Comment by k-rister** [comment]
@atheurer 

FYI, I accidentally submitted that last message before it was completed so I edited it to contain everything.  So the notification in your inbox is not a complete message...

**Pull request merged**
