### PR TITLE
JSON messaging format

### PR DESCRIPTION
**Pull request by k-rister**

### CODE REVIEW

**Comment by k-rister** [comment]
I have the (or at least a draft) of the new JSON based messaging format working.

I'm still working on it though so this is a DO_NOT_MERGE.

So far this is just a drop-in replacement implementation which maintains the communication silos that are currently in place (leader->follower(s), followerN->leader).  The next step is to re-work the messaging logic so that the messages are more broadly visible to all participants and get rid of the silo approach.

**Comment by k-rister** [comment]
Here is output from the `test/run-test.sh` script in "standard" mode: [test.standard.txt](https://gist.github.com/k-rister/49baba7bb28e82e0f99a63140693cfd8)

**Comment by k-rister** [comment]
Here is output from the `test/run-test.sh` script in "debug" mode: [test.debug.txt](https://gist.github.com/k-rister/79eedf6f6322af805c860542ad2b9cae)

There is obviously a lot to take in here, but the big take away is you can see the message traffic is being seen by all the participants and they are choosing whether or not to process the messages depending on their intended recipient.

**Comment by k-rister** [comment]
Updated  "standard" mode output: [test.standard.txt](https://gist.github.com/k-rister/8951a7e9ab1f3271a363c1b85b0b8049)

**Comment by k-rister** [comment]
@atheurer Note that there are two small changes to the CLI interface, otherwise everything else should be internal changes that don't affect using this at the moment.

The changes are the creation of a required `--leader-id=<id>` option so that followers know who the leader is and I "fixed" the `--abort` option so that now it doesn't require a value (it is either present or not).

**Comment by atheurer** [comment]
I think I need some clarification on the use of --leader-id.  Is it necessary for roadblock to function?  Or are you just forcing it to make it very obvious to the clients that they must know what to look for in the messages to find out what the leader sent?

**Comment by k-rister** [comment]
> I think I need some clarification on the use of --leader-id. Is it necessary for roadblock to function? Or are you just forcing it to make it very obvious to the clients that they must know what to look for in the messages to find out what the leader sent?

The messages that a participant sends now are either broadcast to "all" or specifically directed at a particular participant.  It would be possible for the followers to just blast their messages to "all" and then only the leader to process them, but I chose to add the `--leader-id` so that the followers could specifically address their messages to the leader.  So as currently written the followers absolutely need to know the ID of the leader so the know who to send their messages to.

**Comment by atheurer** [comment]
OK, so a follower can send a message to a specific other follower (only)?

**Comment by k-rister** [comment]
> OK, so a follower can send a message to a specific other follower (only)?

Any participant (ie. leader or follower(s)) can directly send a message any other participant or can broadcast a message to all participants.  At this point, the only direct messages being sent are leader->follower or follower->leader but this could change in the future if we want.

**Comment by atheurer** [comment]
I have the new version of roadblock working with the existing functionality I used.  I did not see any option to send a custom message, at least from a cmdline argument.  Did I miss something?

**Comment by k-rister** [comment]
> I have the new version of roadblock working with the existing functionality I used. I did not see any option to send a custom message, at least from a cmdline argument. Did I miss something?

No, this first PR just lays the foundation for the new features that we want to add while maintaining feature parity with what we previously had.  The next set of changes I work on will be to add your custom message requirement.

**Pull request merged**
